title: Lab Notes Theme
description: A documentation theme for GitHub Pages.
favicon: /assets/img/favicon.ico
logo: /assets/img/dos_seal.svg
show_downloads: true
author: Bureau of Global Public Affairs (GPA) Digital Lab Team
author_homepage: https://github.com/IIP-Design

highlighter: rouge
