title: Lab Notes Theme
author: Bureau of Global Public Affairs (GPA) Digital Lab Team
author_homepage: https://github.com/IIP-Design
description: A documentation theme for GitHub Pages.
favicon: /assets/img/favicon.ico
logo: /assets/img/dos_seal.svg
show_downloads: true
show_nav: false

remote_theme: IIP-Design/lab-notes

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
